name: Build and Zip Chrome Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build Chrome
        run: yarn build:chrome

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kinesis-tracker-web-extension-chrome-v${{ steps.package-version.outputs.version }}
          path: dist_chrome
