name: Create tag and release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    outputs:
      version: ${{ steps.check-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Extract version from branch name
        id: check-version
        run: |
          SOURCE_BRANCH_NAME=${{ github.head_ref }}
          if [[ "$SOURCE_BRANCH_NAME" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION=${BASH_REMATCH[0]}
            echo "version=$VERSION" 
          else
            echo "version="
          fi >> $GITHUB_OUTPUT
        shell: bash
  create-tag:
    runs-on: ubuntu-latest
    needs: ["check-commit"]
    if: ${{ needs.check-commit.outputs.version != '' }}
    outputs:
      tag-exists: ${{ steps.create-tag.outputs.tag_exists }}
      release-body: ${{ steps.generate-body.outputs.body }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate body
        id: generate-body
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          git_logs=$(git log "$(git describe --tags --abbrev=0)"..HEAD --oneline)
          git_logs="${git_logs//$'\n'/$'\n'- }"
          {
              echo "body<<$EOF"
              echo "- $git_logs"
              echo "$EOF"
          } >>"$GITHUB_OUTPUT"
        shell: bash
      - uses: rickstaa/action-create-tag@v1
        id: create-tag
        with:
          tag: ${{ needs.check-commit.outputs.version }}
          tag_exists_error: true
          message: ${{ needs.check-commit.outputs.version }}
  create-release:
    runs-on: ubuntu-latest
    needs: ["check-commit", "create-tag"]
    if: ${{ needs.create-tag.outputs.tag-exists == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.check-commit.outputs.version }}
          name: ${{ needs.check-commit.outputs.version }}
          body: ${{ needs.create-tag.outputs.release-body }}
