name: Check Version

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  compare-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Compare release and package versions
        run: |
          SOURCE_BRANCH_NAME=${{ github.head_ref }}
          if [[ "$SOURCE_BRANCH_NAME" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            RELEASE_VERSION=${BASH_REMATCH[0]}
            PACKAGE_VERSION=$(git show HEAD:package.json | jq -r .version)
            echo "Version Release: $RELEASE_VERSION, Package : $PACKAGE_VERSION"
            if [[ "${RELEASE_VERSION:1}" != "$PACKAGE_VERSION" ]]; then
              exit 1
            else
              echo "Version matched."
            fi
          else
            echo "Version format does not matched."
            exit 1
          fi
        shell: bash
