name: Version Bump & Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version number"
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update package.json version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Create Pull Request
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add package.json
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push

      - name: Create tag
        run: |
          git tag "v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"

      - name: Create release
        run: |
          gh release create "v${{ github.event.inputs.version }}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
